### PR TITLE
Onetime functionality

### PR DESCRIPTION
**Pull request by budRich**
this patch adds `-o` option. If set, xnotify will terminate after the first notifications timeout is reached.

with this functionality together with #1 one can achieve a simple yet dynamic notification center.

f.i. One can have a normal xnotify process reading from a fifo:
```
mkfif /tmp/xnotify.fifo
cat /tmp/xnotify.fifo > xnotify -G SE &
```

But also spawn context specific onetime notifications at the same time:

``` bash
#!/bin/bash
[[ everything_beautiful = must_die ]] && { echo "its true you know" | xnotify -c '#FF0000' -s 5 -o -G NW   ;}
echo notification has been shown
```

It can also be used to "pause" execution of a script (like example above).

### CODE REVIEW

**Comment by phillbush** [comment]
Nice addition.
I'm gonna merge it and do some modifications, in special, remove the `onetime` flag from the `config` structure since it is not set on `config.h` at compile time, but on command line option at runtime, and adapt the indentation and comment style to the rest of the program.

One downside of this `-o` option is that it does not queue the notifications, so if you invoke two `xnotify` instances at the same time the notifications will overlap one another. Cating a fifo into `xnotify` and echoing a line on demand queue the notifications, since only a single `xnotify` instance would be involved.

**Comment by phillbush** [comment]
I removed xnotify.h accidentally, I was supposed to just remove a line...

**Comment by phillbush** [comment]
I removed the `-o` flag and made the one-time behavior the default behavior for xnotify.  
(That is, now when you `echo Hello World | xnotify`, xnotify will exit when the notification is done).

**Comment by budRich** [comment]
sweet!

**Pull request merged**
